; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 11 2020 20:25:39 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
;M116 P0

