; Trigger file to power on Duet 3 while printer is in standby mode
; generated by David Husolo
;When trigger2 state changes it calls "Power On" macro file.

M98 P"/macros/Power On"								; calls power on macro