; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 11 2020 20:25:38 GMT-0500 (Central Daylight Time)
M280 P0 S90 ; retract BLTouch

