; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 11 2020 20:25:39 GMT-0500 (Central Daylight Time)

M106 S0