; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 09 2018 13:27:56 GMT+0300
G91                 ; relative positioning
G1 H2 Z5 F6000      ; lift Z relative to current position
G90                 ; absolute positioning
G1 X194 Y138 F6000 ; go to first probe point
;My probe is on the left of my hotend. The coordinate put the BLTouch in the center of the bed.
G30                 ; home Z by probing the bed
